apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../quickstart.yml
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: kratos-selfservice-ui-react
  name: kratos-selfservice-ui-react
spec:
  containers:
    - env:
        - name: COOKIE_SECRET
          value: changeme
        - name: CSRF_COOKIE_NAME
          value: cookie_name
        - name: CSRF_COOKIE_SECRET
          value: changeme
        - name: DANGEROUSLY_DISABLE_SECURE_CSRF_COOKIES
          value: "true"
        - name: HYDRA_ADMIN_URL
          value: http://hydra:4445
        - name: KRATOS_ADMIN_URL
          value: http://kratos:4434
        - name: KRATOS_PUBLIC_URL
          value: http://kratos:4433
        - name: NEXT_PUBLIC_HYDRA_ADMIN_URL
          value: http://hydra:4445
        - name: NEXT_PUBLIC_KRATOS_ADMIN_URL
          value: http://kratos:4434
        - name: NEXT_PUBLIC_KRATOS_BROWSER_URL
          value: http://0.0.0.0:4433
        - name: NEXT_PUBLIC_KRATOS_PUBLIC_URL
          value: http://kratos:4433
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "4455"
      image: kratos-selfservice-ui-react
      name: kratos-selfservice-ui-react
      ports:
        - containerPort: 4455
          protocol: TCP
  restartPolicy: OnFailure
