apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../quickstart.yml
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: kratos
  name: kratos
spec:
  ports:
    - name: "4433"
      port: 4433
      targetPort: 4433
    - name: "4434"
      port: 4434
      targetPort: 4434
  selector:
    io.kompose.service: kratos
