dsn: memory

identity:
  default_schema_id: default
  schemas: 
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

serve:
  public:
    base_url: http://0.0.0.0:4433
    cors:
      enabled: true
      allowed_origins:
        - http://0.0.0.0:3000
        - http://0.0.0.0:4455
      allow_credentials: true
      allowed_headers:
        - Content-Type
        - Cookie
        - X-CSRF-Token
      exposed_headers:
        - Content-Type
  admin:
    base_url: http://0.0.0.0:4434

session:
  whoami:
    required_aal: highest_available

selfservice:
  default_browser_return_url: http://0.0.0.0:4455/
  allowed_return_urls:
    - http://0.0.0.0:4455
    - http://0.0.0.0:3000

  methods:
    lookup_secret:
      enabled: true
    code:
      enabled: true
      mfa_enabled: true
      passwordless_enabled: false
    totp:
      config:
        issuer: Demo App
      enabled: true
    password:
      enabled: true
      config:
        min_password_length: 6
        identifier_similarity_check_enabled: false
        haveibeenpwned_enabled: false

  flows:
    recovery:
      after:
        hooks: []
      before:
        hooks: []
      enabled: true
      lifespan: 30m0s
      notify_unknown_recipients: false
      ui_url: http://0.0.0.0:4455/recovery
      use: code
    
    verification:
      after:
        hooks: []
      before:
        hooks: []
      enabled: true
      lifespan: 30m0s
      notify_unknown_recipients: false
      ui_url: http://0.0.0.0:4455/verification
      use: code

    error:
      ui_url: http://0.0.0.0:4455/error

    settings:
      ui_url: http://0.0.0.0:4455/settings
      privileged_session_max_age: 1m
      required_aal: highest_available

    logout:
      after:
        default_browser_return_url: http://0.0.0.0:4455/login

    login:
      ui_url: http://0.0.0.0:4455/login

    registration:
      ui_url: http://0.0.0.0:4455/registration
      after:
        password:
          hooks:
            - hook: session

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

oauth2_provider:
  url: http://hydra:4445
